title: Jui-Jia (Rebecca) Chen # your name (or website title) here
logo: "/images/rebecca.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science, Data Analytics, Machine Learning | Columbia MSOR Alum | Data Storyteller
  <br><br>
  Tech Stack: Python, SQL, Tableau, Power BI, Excel, Scikit-learn
  <br><br>
  <a href="https://www.linkedin.com/in/juijiachen/?trk=opento_sprofile_details">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
